### ISSUE TITLE
Dependency on vmath?

### ISSUE THREAD

**Issue by zacharycarter** [treeform/windy#36]
I don't understand the logic here - why tightly couple this project with another dependency like vmath? IMO users shouldn't have to buy into your linear algebra library to use your windowing library. This is the same type of issue I have with fidget but even more egregious...

**Comment by guzba** [comment]
We need a data structure to represent window position, mouse position, window size, framebuffer size, etc. An Ivec works great for this. You don't need to use vmath for anything beyond that and can easily turn it into whatever representation you want with a converter if typing it the few places you need to is too inconvenient.

**Comment by guzba** [comment]
Could you expand on what you'd like to receive from `window.pos` and pass in to `window.pos = ` as an example? Right now this issue is just a complaint with no productive suggestions.

**Comment by zacharycarter** [comment]
> Could you expand on what you'd like to receive from `window.pos` and pass in to `window.pos = ` as an example? Right now this issue is just a complaint with no productive suggestions.

I apologize, however I have tried to express to @treeform in the past my desire to see some of the libraries you all maintain become more friendly to developers who do not want to depend on some of the same technologies you all depend on, and I think each time we quickly run into a wall in our discussions.

If you take this library for instance - you could easily use a concept here or a tuple or two thirty-two bit signed integers, whatever... Instead I must now include and use vmath in my project because you all have made that decision for me as a user of your library. I understand you all use vmath, but that doesn't mean I want to have to add another dependency to my project in order to use a windowing library. I apparently also am forced to use OpenGL for whatever reason to use this library - these things don't make sense. Why do I need to be forced to use a certain graphics API in order to have cross platform windowing? I don't have this limitation with any other windowing library - why do we have it here?

It's the same thing with fidget and requiring me to use glfw and opengl with it - I understand you all use these technologies, however your potential users may not. Maybe they want to use SDL2 or maybe they don't want your GUI library to have control over their application's event loop. Fidget is more of a runtime, similar to Qt at this point vs being an actual GUI library.

Also - from what I've witnessed in discord / irc, when folks ask for recommendations for libraries lately, the libraries you all work on get mentioned quite frequently. I do think you both do great work, but I'd encourage you to take more time ensuring your code is correct - https://github.com/treeform/windy/blob/master/src/windy/platforms/win32/platform.nim#L10-L21 | https://play.nim-lang.org/#ix=3EnA

**Comment by treeform** [comment]
Hey Zachary, we use what we use because what we write we write for us. 

At first we started out not using vmath, but we quickly needed position vector thingy, why reinvent the wheel? 

Big part of this library is setting up OpenGL context, because its complex. Just like GLFW, its the main point of this lib.

I am not sure what your bug is about #defines are "typeless" in C. In Nim they get cast to proper type when passed to a function. Is there some thing I am missing? Nim default int is 64bit while C default int is 32bit its not us...

Thank you for noticing our great work!

**Comment by guzba** [comment]
> I apparently also am forced to use OpenGL for whatever reason to use this library - these things don't make sense. Why do I need to be forced to use a certain graphics API in order to have cross platform windowing?

As was noted by treeform, essentially all of the repos have been written to meet the needs of our own projects. Some are more opinionated than others. Windy is an opinionated repo so far. You may not agree with the choices, and in that case you can of course offer suggestions or simply not use them. For example, both of us are actually partial to the "no dependencies" appeal. However that has to balance against how we're going to use the lib ourselves and how impactful the dep is.

For example, here you could trivially write a wrapper Nim file that brings windy in, and exports a non-vmath API. This quarantines vmath and it'd be done in 15 mins. The alternative is tuples or a windy-specific type, both of which don't actually help since you'll need to still unpack your data rep into the windy data rep.

As for OpenGL, we make that very clear from the readme. We are not out to write the most flexible windowing library with the ability to use any graphics API. That's a ton more work, and also zero benefit to us. Maybe we will in the future? If Windy doesn't meet your needs, obv its not a good fit for you and you can use something else or write your own.

> I'd encourage you to take more time ensuring your code is correct - https://github.com/treeform/windy/blob/master/src/windy/platforms/win32/platform.nim#L10-L21 | https://play.nim-lang.org/#ix=3EnA

Your playground example is not relevant as that is not how we actually use the constants. See https://github.com/treeform/windy/blob/master/src/windy/platforms/win32/platform.nim#L840

I would encourage you to take more time to ensure your review is correct ;) lol just being snarky back.

**Comment by beef331** [comment]
> Could you expand on what you'd like to receive from `window.pos` and pass in to `window.pos = ` as an example? Right now this issue is just a complaint with no productive suggestions.

If you want a sincere suggestion you could use a concept for this to allow any vector library to be used without having to depend anyone's vector library.
```nim
type 
  IntVec2* = concept i
    i.x is int
    i.y is int
    i.x = default(int)
    i.y = default(int)
  Window*[T: IntVec2] = ref object
    size*: T
 ```

**Comment by guzba** [comment]
Concepts do seem promising and I would like them if we could get them to fit here, but I run into an issue pretty fast unfortunately.

Windy needs to hold on to all open windows (seq[Window] currently) to handle events from the OS and send them to the correct callbacks, etc. See https://github.com/treeform/windy/blob/master/src/windy/platforms/win32/platform.nim#L75 and https://github.com/treeform/windy/blob/master/src/windy/platforms/win32/platform.nim#L579

It appears concepts work a bit like generics in that the type needs to be tagged on the type [T: IntVec2]. I am not aware of how to make this work with the global seq that is needed for processing OS events since does not know what type the Window T was solved for. Is there a trick or something about concepts I am missing that could help here?

**Comment by beef331** [comment]
Ah yea that's a tricky one to work around, I can only think about the following:
```nim
type 
  IntVec2* = concept i
    i.x is int
    i.y is int
    i.x = default(int)
    i.y = default(int)
  Window*[T: IntVec2] = ref object
    size*: T
    pos*: T

# In module 'windyvector' or w/e
import std/macros
var windyVector {.compileTime.}: NimNode
macro setWindyVector(v: typedesc[IntVec2]) = windyVector = v
macro getWindyVector(): untyped =
  if windyVector.isNil:
    error("use `setWindyVector` to supply your Vector type before here")
  windyVector
  
# In the user's module:
# import `windy/vector` not ideal as import order now matters sadly
setWindyVector(tuple[x: int, y: int])
# import windy

# In your module:
var windows: seq[Window[getWindyVector]]
echo typeof(windows)

# Just some more example code
type IVec2 = object
  x, y: int
setWindyVector(IVec2)
echo typeof(Window[getWindyVector])
```

**Comment by beef331** [comment]
Have thought about it more and maybe something like this may be passable as a use case, still not great though:
```nim
type
  IntVec2* = concept i
    i.x is int
    i.y is int
    i.x = default(int)
    i.y = default(int)

type 
  Window*[T: IntVec2] = object
    size*: T
    pos*: T

template implWindy(T: typedesc[IntVec2]) = 
  var a: seq[Window[T]]
  proc addWindow(w: Window[T]) = 
    a.add(w)

  proc echoWindows(_: typedesc[T]) = echo a

implWindy(tuple[x: int, y: int])
addWindow(Window[tuple[x: int, y: int]](size: (10, 20), pos: (20, 4)))
addWindow(Window[tuple[x: int, y: int]](size: (30, 20), pos: (50, 4)))

type SomeVector = object
  x,y: int
implWindy(SomeVector)
addWindow(Window[SomeVector](size: SomeVector(x: 10, y: 20), pos: SomeVector(x: 10, y: 20)))
addWindow(Window[SomeVector](size: SomeVector(x: 20, y: 20), pos: SomeVector(x: 60, y: 20)))

echoWindows(SomeVector)
echoWindows(tuple[x: int, y: int])
```

**Comment by treeform** [comment]
Hey, sorry we just like vectors from vmath and will probably just stick with them. It's not just IVec2 we also need to use the float Vec2 for scrolling and probably more things in the future. Not using vmath just makes it frustrating for us.

We do not like having unnecessary dependancies but this is a tough one.

Thank you for your input, but I will close this issue.
